title: Jennifer Felton # your name (or website title) here
logo: "/images/profileCircle.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science student at California State University, Fullerton; currently pursing intrests in game design, augmented reality and AI. 
  <br><br>
  <a href="https://www.linkedin.com/in/jenniferafelton/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
